basePath: /
definitions:
  app.loginReq:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  app.loginResp:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      login:
        type: string
      role:
        type: string
      token_type:
        type: string
    type: object
  app.registerReq:
    properties:
      login:
        description: лучше назвать то же самое что login
        type: string
      password:
        type: string
    type: object
  app.registerResp:
    properties:
      ok:
        type: boolean
    type: object
  ds.ModConfirm:
    properties:
      confirm:
        type: string
    type: object
  ds.OrderSynthesisRequestBody:
    properties:
      additional_conditions:
        type: string
      status:
        type: string
      substances:
        type: string
      user_name:
        type: string
    type: object
  ds.Substances:
    properties:
      ID:
        type: integer
      class:
        type: string
      formula:
        type: string
      image:
        type: string
      status:
        type: string
      title:
        type: string
    type: object
  ds.Syntheses:
    properties:
      additional_conditions:
        type: string
      date_created:
        type: string
      date_finished:
        type: string
      date_processed:
        type: string
      id:
        type: integer
      moderator:
        type: string
      name:
        type: string
      status:
        type: string
      time:
        type: string
      user_name:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Возвращает jwt токен
      parameters:
      - description: Тело запроса на вход
        in: body
        name: request_body
        required: true
        schema:
          $ref: '#/definitions/app.loginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.loginResp'
      summary: Войти в систему
      tags:
      - Аутентификация
  /logout:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Выйти из системы
      tags:
      - Аутентификация
  /register:
    post:
      consumes:
      - application/json
      description: Добавляет нового пользователя в БД
      parameters:
      - description: Тело запроса
        in: body
        name: request_body
        required: true
        schema:
          $ref: '#/definitions/app.registerReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.registerResp'
      summary: Зарегистрировать нового пользователя
      tags:
      - Аутентификация
  /substances:
    get:
      consumes:
      - application/json
      description: Вовзращает все субстанции
      parameters:
      - description: Имя субстанции
        in: query
        name: name_pattern
        type: string
      - description: Статус субстанции
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Список субстанций
      tags:
      - Субстанции
  /substances/{substance}:
    get:
      description: Возвращает одну субстанцию по имени
      parameters:
      - description: Имя субстанции
        in: path
        name: substance
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Субстанция
          schema:
            type: string
      summary: Одна субстанция
      tags:
      - Субстанции
  /substances/{substance}/add_image:
    post:
      description: Добавляет изображение к субстанции + на минио сервер
      parameters:
      - description: ID Субстанции
        in: path
        name: substance
        required: true
        type: integer
      - description: Изображение
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Картинка загружена
          schema:
            type: string
      summary: Добавить изображение
      tags:
      - Субстанции
  /substances/{substance}/delete:
    delete:
      description: Меняет статус субстанции на "Удалён"
      parameters:
      - description: Имя субстанции
        in: path
        name: substance
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Substance was successfully deleted
          schema:
            type: string
      summary: Удалить субстанцию
      tags:
      - Субстанции
  /substances/{substance}/edit:
    put:
      consumes:
      - application/json
      description: Ищет субстанцию по имени и меняет её
      parameters:
      - description: Отредактированная субстанция
        in: body
        name: substance
        required: true
        schema:
          $ref: '#/definitions/ds.Substances'
      - description: Имя субстанции
        in: query
        name: title
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Found
          schema:
            type: string
      summary: Редактировать субстанцию
      tags:
      - Субстанции
  /substances/add:
    post:
      consumes:
      - application/json
      description: Создает новую субстанцию из паркметров JSON
      parameters:
      - description: Детали новой субстанции
        in: body
        name: substance
        required: true
        schema:
          $ref: '#/definitions/ds.Substances'
      produces:
      - application/json
      responses:
        "201":
          description: Substance created successfully
          schema:
            type: string
      summary: Добавляет субстанцию
      tags:
      - Субстанции
  /syntheses:
    get:
      description: Получает все синтезы
      parameters:
      - description: Первая дата
        in: query
        name: date1
        type: string
      - description: Вторая дата
        in: query
        name: date2
        type: string
      - description: Статус
        in: query
        name: status
        type: string
      - description: Создатель
        in: query
        name: creator
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Список синтезов
      tags:
      - Синтезы
  /syntheses/{synthesis}:
    get:
      description: Возвращает синтез по ID
      parameters:
      - description: Synthesis ID
        in: path
        name: synthesis
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Один синтез
      tags:
      - Синтезы
  /syntheses/{synthesis}/apply:
    put:
      consumes:
      - application/json
      description: Меняет статус заявки на выбранный
      parameters:
      - description: Статус
        in: body
        name: synthesis_body
        required: true
        schema:
          $ref: '#/definitions/ds.ModConfirm'
      - description: ID Синтеза
        in: path
        name: synthesis
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Поменять статус заявки (синтеза) как модератор
      tags:
      - Синтезы
  /syntheses/{synthesis}/apply_user:
    put:
      consumes:
      - application/json
      description: Меняет статус как лаборант
      parameters:
      - description: ID Синтеза
        in: path
        name: synthesis
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
      summary: Поменять статус синтезу как лаборант
      tags:
      - Синтезы
  /syntheses/{synthesis}/delete:
    delete:
      description: Меняет статус синтеза на "Удалён"
      parameters:
      - description: ID Синтеза
        in: path
        name: synthesis
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Synthesis was successfully deleted
          schema:
            type: string
      summary: Удаляет синтез
      tags:
      - Синтезы
  /syntheses/{synthesis}/edit:
    put:
      consumes:
      - application/json
      description: Ищет синтез по ID
      parameters:
      - description: Отредактированный синтез
        in: body
        name: synthesis_body
        required: true
        schema:
          $ref: '#/definitions/ds.Syntheses'
      - description: ID Синтеза
        in: query
        name: synthesis
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Редактировать синтез
      tags:
      - Синтезы
  /syntheses/generate:
    put:
      consumes:
      - application/json
      description: Создаёт новый/находит существующий синтез и добавляет к нему субстанции
      parameters:
      - description: Параметры заказа
        in: body
        name: request_body
        required: true
        schema:
          $ref: '#/definitions/ds.OrderSynthesisRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
      summary: Заказать синтез
      tags:
      - Синтезы
  /synthesis_substance/{id1}/{id2}:
    put:
      description: Ищет связь синтеза с субстанцией и удаляет её
      parameters:
      - description: ID Синтеза
        in: path
        name: id1
        required: true
        type: integer
      - description: ID Субстанции
        in: path
        name: id2
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
      summary: Удалить связь синтеза с субстанцией
      tags:
      - Синтезы
swagger: "2.0"
